daysUntilStale: 30
daysUntilClose: 7
exemptLabels:
 - pinned
 - security
staleLabel: wontfix
markComment: >
 This issue has automatically marked as stale because it has not had any kind of recent activity. It will be closed if no further activity occurs. Thank you for your contribution.
closeComment: false